# Generated by Django 5.1.2 on 2024-10-16 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='summary',
            new_name='JobTitle',
        ),
        migrations.AddField(
            model_name='job',
            name='EndDate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='job',
            name='StartDate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
