# Generated by Django 5.1.2 on 2024-10-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_rename_summary_job_jobtitle_job_enddate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Description',
            field=models.CharField(default='', max_length=20000),
        ),
        migrations.AddField(
            model_name='job',
            name='Location',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='job',
            name='JobTitle',
            field=models.CharField(default='', max_length=250),
        ),
    ]
