# Generated by Django 5.1.2 on 2024-10-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_description_job_location_alter_job_jobtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Description',
            field=models.CharField(max_length=20000),
        ),
        migrations.AlterField(
            model_name='job',
            name='JobTitle',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='job',
            name='Location',
            field=models.CharField(max_length=200),
        ),
    ]
