# Generated by Django 5.1.2 on 2024-10-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_alter_job_description_alter_job_jobtitle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Employeer',
            field=models.CharField(default='', max_length=250),
        ),
    ]
