# Generated by Django 5.1.2 on 2024-10-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_employeer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Employeer',
            field=models.CharField(max_length=250),
        ),
    ]
