# Generated by Django 5.1.2 on 2024-10-16 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_alter_job_employeer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Description',
            field=models.TextField(max_length=20000),
        ),
    ]
