# Generated by Django 5.1.2 on 2024-10-22 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_project_description_project_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.ImageField(default=' ', upload_to='images/'),
        ),
    ]
