# Generated by Django 5.1.2 on 2024-11-05 20:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_alter_job_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default=' ', upload_to='images/')),
                ('nameOfSchool', models.CharField(default=' ', max_length=100)),
                ('major', models.CharField(default=' ', max_length=150)),
                ('degree', models.CharField(default=' ', max_length=150)),
                ('StartDate', models.DateField(default=datetime.date.today)),
                ('EndDate', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.AddField(
            model_name='job',
            name='current',
            field=models.BooleanField(default=False),
        ),
    ]
